feat: Add save/restore state commands
nextcloud-libraries/nextcloud-cypress pull request #627
Opened 2024-09-15 11:42 UTC by artonge

2024-09-16 14:49 UTC, skjnldsv commented on lib/index.ts
> +			 *
```suggestion
```

2024-09-16 14:56 UTC, skjnldsv approved these changes

2024-09-17 08:22 UTC, skjnldsv requested changes
You are using the `nextcloud-cypress-tests_groupfolders` container name :see_no_evil:

2024-09-17 08:23 UTC, skjnldsv commented
I remember I also did this already a month ago https://github.com/nextcloud-libraries/nextcloud-cypress/blob/main/lib/commands/snapshots.ts

Wanna add te data part to it instead?

2024-09-17 09:02 UTC, artonge commented
Ah, I looked for that but couldn't find it. Let me upgrade it

2024-09-17 09:05 UTC, artonge commented
Ah, I was looking in the master branch :see_no_evil:

2024-09-17 09:57 UTC, skjnldsv approved these changes

2024-09-17 10:11 UTC, merged